server:
  port: 8800
spring:
  application:
    name: book-server
  datasource:
    url: jdbc:mysql://47.93.176.203:3306/mall_book
    username: mikasa
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true