server:
  port: 8801
spring:
  application:
    name: book-server
  datasource:
    url: jdbc:mysql://imikasa.com:3307/mall_book
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  redis:
    host: imikasa.com
    port: 6379
    lettuce:
      pool:
        max-active: 8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.imikasa.mapper: trace
    com.imikasa.service.impl: trace